version: "3.8"

services:

  app:
    # TODO: only build from the web once GitHub Container Registry is working with docker-compose
#    build: https://github.com/uberfastman/fantasy-football-metrics-weekly-report.git
    build: .
    ports:
      - "4000:4000"
    environment:
      - FLASK_APP=api.py
    volumes:
      # TODO: swap ".:/app" with commented out volumes once GitHub Container Registry is working with docker-compose
      - .:/app
#      - api:/app/api
#      - ./api:/api
#      - ./config.ini:/api/config.ini
    depends_on:
      - redis_db
    entrypoint: ["flask", "run", "-p", "4000", "--host", "0.0.0.0"]

  redis_db:
    image: redis

#volumes:
#  api: